LIBNAME = OpenFlowLib

MLIFILES = _build/OpenFlow0x01.mli \
           _build/OpenFlow0x01_Parser.mli \
           _build/OpenFlow0x01_Platform.mli \
           _build/OpenFlow0x01_TestPlatform.mli

include ../Makefile.common
