#!/usr/bin/env python

from optical import LINCNet, LINCSwitch, LINCLink

from mininet.node import OVSSwitch, RemoteController
from mininet.cli import CLI
from mininet.net import Mininet
from mininet.log import lg, info, error, debug, output

def start(ip="127.0.0.1",port=6633):

    # Set up logging etc.
    lg.setLogLevel('info')
    lg.setLogLevel('output')

    ctrlr = lambda n: RemoteController(n, ip=ip, port=port, inNamespace=False)
    net = LINCNet(switch=OVSSwitch, controller=ctrlr, listenPort=6635)
    c1 = net.addController('c1')

    ####### End of static Mininet prologue ######

    Abilene = net.addSwitch('s1', dpid='00:00:00:00:00:01', cls=LINCSwitch)
    Dallas = net.addSwitch('s2', dpid='00:00:00:00:00:02', cls=LINCSwitch)
    ElPaso = net.addSwitch('s3', dpid='00:00:00:00:00:03', cls=LINCSwitch)
    Albany = net.addSwitch('s4', dpid='00:00:00:00:00:04', cls=LINCSwitch)
    Boston = net.addSwitch('s5', dpid='00:00:00:00:00:05', cls=LINCSwitch)
    Syracuse = net.addSwitch('s6', dpid='00:00:00:00:00:06', cls=LINCSwitch)
    Albuquerque = net.addSwitch('s7', dpid='00:00:00:00:00:07', cls=LINCSwitch)
    Denver = net.addSwitch('s8', dpid='00:00:00:00:00:08', cls=LINCSwitch)
    LasVegas = net.addSwitch('s9', dpid='00:00:00:00:00:09', cls=LINCSwitch)
    Atlanta = net.addSwitch('s10', dpid='00:00:00:00:00:0a', cls=LINCSwitch)
    Birmingham = net.addSwitch('s11', dpid='00:00:00:00:00:0b', cls=LINCSwitch)
    Charlotte = net.addSwitch('s12', dpid='00:00:00:00:00:0c', cls=LINCSwitch)
    Jacksonville = net.addSwitch('s13', dpid='00:00:00:00:00:0d', cls=LINCSwitch)
    Austin = net.addSwitch('s14', dpid='00:00:00:00:00:0e', cls=LINCSwitch)
    Houston = net.addSwitch('s15', dpid='00:00:00:00:00:0f', cls=LINCSwitch)
    SanAntonio = net.addSwitch('s16', dpid='00:00:00:00:00:10', cls=LINCSwitch)
    Baltimore = net.addSwitch('s17', dpid='00:00:00:00:00:11', cls=LINCSwitch)
    Philadelphia = net.addSwitch('s18', dpid='00:00:00:00:00:12', cls=LINCSwitch)
    Pittsburgh = net.addSwitch('s19', dpid='00:00:00:00:00:13', cls=LINCSwitch)
    WashingtonDC = net.addSwitch('s20', dpid='00:00:00:00:00:14', cls=LINCSwitch)
    BatonRouge = net.addSwitch('s21', dpid='00:00:00:00:00:15', cls=LINCSwitch)
    NewOrleans = net.addSwitch('s22', dpid='00:00:00:00:00:16', cls=LINCSwitch)
    Billings = net.addSwitch('s23', dpid='00:00:00:00:00:17', cls=LINCSwitch)
    Bismarck = net.addSwitch('s24', dpid='00:00:00:00:00:18', cls=LINCSwitch)
    Spokane = net.addSwitch('s25', dpid='00:00:00:00:00:19', cls=LINCSwitch)
    Nashville = net.addSwitch('s26', dpid='00:00:00:00:00:1a', cls=LINCSwitch)
    Minneapolis = net.addSwitch('s27', dpid='00:00:00:00:00:1b', cls=LINCSwitch)
    Providence = net.addSwitch('s28', dpid='00:00:00:00:00:1c', cls=LINCSwitch)
    Buffalo = net.addSwitch('s29', dpid='00:00:00:00:00:1d', cls=LINCSwitch)
    Cleveland = net.addSwitch('s30', dpid='00:00:00:00:00:1e', cls=LINCSwitch)
    Rochester = net.addSwitch('s31', dpid='00:00:00:00:00:1f', cls=LINCSwitch)
    Charleston = net.addSwitch('s32', dpid='00:00:00:00:00:20', cls=LINCSwitch)
    Raleigh = net.addSwitch('s33', dpid='00:00:00:00:00:21', cls=LINCSwitch)
    Greensboro = net.addSwitch('s34', dpid='00:00:00:00:00:22', cls=LINCSwitch)
    Chicago = net.addSwitch('s35', dpid='00:00:00:00:00:23', cls=LINCSwitch)
    Detroit = net.addSwitch('s36', dpid='00:00:00:00:00:24', cls=LINCSwitch)
    Milwaukee = net.addSwitch('s37', dpid='00:00:00:00:00:25', cls=LINCSwitch)
    Springfield = net.addSwitch('s38', dpid='00:00:00:00:00:26', cls=LINCSwitch)
    Cincinnati = net.addSwitch('s39', dpid='00:00:00:00:00:27', cls=LINCSwitch)
    Columbus = net.addSwitch('s40', dpid='00:00:00:00:00:28', cls=LINCSwitch)
    Louisville = net.addSwitch('s41', dpid='00:00:00:00:00:29', cls=LINCSwitch)
    Toledo = net.addSwitch('s42', dpid='00:00:00:00:00:2a', cls=LINCSwitch)
    LittleRock = net.addSwitch('s43', dpid='00:00:00:00:00:2b', cls=LINCSwitch)
    OklahomaCity = net.addSwitch('s44', dpid='00:00:00:00:00:2c', cls=LINCSwitch)
    Omaha = net.addSwitch('s45', dpid='00:00:00:00:00:2d', cls=LINCSwitch)
    SaltLakeCity = net.addSwitch('s46', dpid='00:00:00:00:00:2e', cls=LINCSwitch)
    Tucson = net.addSwitch('s47', dpid='00:00:00:00:00:2f', cls=LINCSwitch)
    Fresno = net.addSwitch('s48', dpid='00:00:00:00:00:30', cls=LINCSwitch)
    LosAngeles = net.addSwitch('s49', dpid='00:00:00:00:00:31', cls=LINCSwitch)
    Oakland = net.addSwitch('s50', dpid='00:00:00:00:00:32', cls=LINCSwitch)
    Richmond = net.addSwitch('s51', dpid='00:00:00:00:00:33', cls=LINCSwitch)
    Hartford = net.addSwitch('s52', dpid='00:00:00:00:00:34', cls=LINCSwitch)
    LongIsland = net.addSwitch('s53', dpid='00:00:00:00:00:35', cls=LINCSwitch)
    Orlando = net.addSwitch('s54', dpid='00:00:00:00:00:36', cls=LINCSwitch)
    KansasCity = net.addSwitch('s55', dpid='00:00:00:00:00:37', cls=LINCSwitch)
    StLouis = net.addSwitch('s56', dpid='00:00:00:00:00:38', cls=LINCSwitch)
    Tulsa = net.addSwitch('s57', dpid='00:00:00:00:00:39', cls=LINCSwitch)
    Phoenix = net.addSwitch('s58', dpid='00:00:00:00:00:3a', cls=LINCSwitch)
    Memphis = net.addSwitch('s59', dpid='00:00:00:00:00:3b', cls=LINCSwitch)
    NewYork = net.addSwitch('s60', dpid='00:00:00:00:00:3c', cls=LINCSwitch)
    SanDiego = net.addSwitch('s61', dpid='00:00:00:00:00:3d', cls=LINCSwitch)
    SantaBarbara = net.addSwitch('s62', dpid='00:00:00:00:00:3e', cls=LINCSwitch)
    Miami = net.addSwitch('s63', dpid='00:00:00:00:00:3f', cls=LINCSwitch)
    Tampa = net.addSwitch('s64', dpid='00:00:00:00:00:40', cls=LINCSwitch)
    WestPalmBeach = net.addSwitch('s65', dpid='00:00:00:00:00:41', cls=LINCSwitch)
    Tallahassee = net.addSwitch('s66', dpid='00:00:00:00:00:42', cls=LINCSwitch)
    Newark = net.addSwitch('s67', dpid='00:00:00:00:00:43', cls=LINCSwitch)
    Scranton = net.addSwitch('s68', dpid='00:00:00:00:00:44', cls=LINCSwitch)
    Wilmington = net.addSwitch('s69', dpid='00:00:00:00:00:45', cls=LINCSwitch)
    Norfolk = net.addSwitch('s70', dpid='00:00:00:00:00:46', cls=LINCSwitch)
    Sacramento = net.addSwitch('s71', dpid='00:00:00:00:00:47', cls=LINCSwitch)
    SanFrancisco = net.addSwitch('s72', dpid='00:00:00:00:00:48', cls=LINCSwitch)
    Portland = net.addSwitch('s73', dpid='00:00:00:00:00:49', cls=LINCSwitch)
    Seattle = net.addSwitch('s74', dpid='00:00:00:00:00:4a', cls=LINCSwitch)
    SanJose = net.addSwitch('s75', dpid='00:00:00:00:00:4b', cls=LINCSwitch)
    net.addLink(Abilene, Dallas, 0, 0, cls=LINCLink)
    net.addLink(Abilene, ElPaso, 1, 0, cls=LINCLink)
    net.addLink(Dallas, Houston, 2, 2, cls=LINCLink)
    net.addLink(Dallas, LittleRock, 3, 0, cls=LINCLink)
    net.addLink(Dallas, OklahomaCity, 4, 0, cls=LINCLink)
    net.addLink(ElPaso, SanAntonio, 2, 1, cls=LINCLink)
    net.addLink(ElPaso, Tucson, 3, 0, cls=LINCLink)
    net.addLink(Albany, Boston, 0, 0, cls=LINCLink)
    net.addLink(Albany, Syracuse, 1, 0, cls=LINCLink)
    net.addLink(Boston, Providence, 1, 0, cls=LINCLink)
    net.addLink(Albuquerque, Dallas, 0, 1, cls=LINCLink)
    net.addLink(Albuquerque, ElPaso, 2, 1, cls=LINCLink)
    net.addLink(Albuquerque, Denver, 1, 0, cls=LINCLink)
    net.addLink(Albuquerque, LasVegas, 3, 0, cls=LINCLink)
    net.addLink(Denver, Omaha, 2, 0, cls=LINCLink)
    net.addLink(Denver, SaltLakeCity, 3, 0, cls=LINCLink)
    net.addLink(LasVegas, SaltLakeCity, 3, 1, cls=LINCLink)
    net.addLink(LasVegas, Phoenix, 2, 0, cls=LINCLink)
    net.addLink(Atlanta, Birmingham, 0, 0, cls=LINCLink)
    net.addLink(Atlanta, Charlotte, 1, 0, cls=LINCLink)
    net.addLink(Atlanta, Jacksonville, 2, 0, cls=LINCLink)
    net.addLink(Birmingham, NewOrleans, 2, 1, cls=LINCLink)
    net.addLink(Birmingham, Nashville, 1, 0, cls=LINCLink)
    net.addLink(Charlotte, Greensboro, 1, 0, cls=LINCLink)
    net.addLink(Jacksonville, Orlando, 2, 0, cls=LINCLink)
    net.addLink(Austin, Houston, 0, 0, cls=LINCLink)
    net.addLink(Austin, SanAntonio, 1, 0, cls=LINCLink)
    net.addLink(Baltimore, Philadelphia, 0, 0, cls=LINCLink)
    net.addLink(Baltimore, Pittsburgh, 1, 0, cls=LINCLink)
    net.addLink(Baltimore, WashingtonDC, 2, 0, cls=LINCLink)
    net.addLink(Philadelphia, Scranton, 2, 1, cls=LINCLink)
    net.addLink(Pittsburgh, Scranton, 2, 2, cls=LINCLink)
    net.addLink(BatonRouge, Houston, 0, 1, cls=LINCLink)
    net.addLink(BatonRouge, NewOrleans, 1, 0, cls=LINCLink)
    net.addLink(NewOrleans, Tallahassee, 2, 0, cls=LINCLink)
    net.addLink(Billings, Denver, 1, 1, cls=LINCLink)
    net.addLink(Billings, Bismarck, 0, 0, cls=LINCLink)
    net.addLink(Billings, Spokane, 2, 0, cls=LINCLink)
    net.addLink(Bismarck, Minneapolis, 1, 0, cls=LINCLink)
    net.addLink(Minneapolis, Omaha, 2, 2, cls=LINCLink)
    net.addLink(Buffalo, Cleveland, 0, 0, cls=LINCLink)
    net.addLink(Buffalo, Rochester, 1, 0, cls=LINCLink)
    net.addLink(Cleveland, Columbus, 1, 1, cls=LINCLink)
    net.addLink(Cleveland, Toledo, 2, 0, cls=LINCLink)
    net.addLink(Rochester, Syracuse, 1, 1, cls=LINCLink)
    net.addLink(Charleston, Jacksonville, 0, 1, cls=LINCLink)
    net.addLink(Charleston, Raleigh, 1, 0, cls=LINCLink)
    net.addLink(Greensboro, Raleigh, 2, 1, cls=LINCLink)
    net.addLink(Greensboro, Louisville, 1, 1, cls=LINCLink)
    net.addLink(Greensboro, Richmond, 3, 0, cls=LINCLink)
    net.addLink(Chicago, Detroit, 0, 0, cls=LINCLink)
    net.addLink(Chicago, Milwaukee, 1, 0, cls=LINCLink)
    net.addLink(Chicago, Springfield, 2, 0, cls=LINCLink)
    net.addLink(Detroit, Toledo, 1, 1, cls=LINCLink)
    net.addLink(Milwaukee, Minneapolis, 1, 1, cls=LINCLink)
    net.addLink(Springfield, StLouis, 1, 2, cls=LINCLink)
    net.addLink(Cincinnati, WashingtonDC, 2, 1, cls=LINCLink)
    net.addLink(Cincinnati, Columbus, 0, 0, cls=LINCLink)
    net.addLink(Cincinnati, Louisville, 1, 0, cls=LINCLink)
    net.addLink(Columbus, Pittsburgh, 2, 1, cls=LINCLink)
    net.addLink(Louisville, Nashville, 2, 1, cls=LINCLink)
    net.addLink(Louisville, StLouis, 3, 1, cls=LINCLink)
    net.addLink(LittleRock, Memphis, 1, 0, cls=LINCLink)
    net.addLink(OklahomaCity, Tulsa, 1, 1, cls=LINCLink)
    net.addLink(Fresno, LasVegas, 0, 1, cls=LINCLink)
    net.addLink(Fresno, LosAngeles, 1, 0, cls=LINCLink)
    net.addLink(Fresno, Oakland, 2, 0, cls=LINCLink)
    net.addLink(LosAngeles, SanDiego, 1, 0, cls=LINCLink)
    net.addLink(LosAngeles, SantaBarbara, 2, 0, cls=LINCLink)
    net.addLink(Oakland, SaltLakeCity, 2, 2, cls=LINCLink)
    net.addLink(Oakland, Sacramento, 1, 0, cls=LINCLink)
    net.addLink(Oakland, SanFrancisco, 3, 0, cls=LINCLink)
    net.addLink(Richmond, WashingtonDC, 1, 2, cls=LINCLink)
    net.addLink(Hartford, Providence, 1, 1, cls=LINCLink)
    net.addLink(Hartford, LongIsland, 0, 0, cls=LINCLink)
    net.addLink(LongIsland, NewYork, 1, 0, cls=LINCLink)
    net.addLink(Orlando, WestPalmBeach, 1, 1, cls=LINCLink)
    net.addLink(KansasCity, Omaha, 0, 1, cls=LINCLink)
    net.addLink(KansasCity, StLouis, 1, 0, cls=LINCLink)
    net.addLink(KansasCity, Tulsa, 2, 0, cls=LINCLink)
    net.addLink(Phoenix, Tucson, 2, 1, cls=LINCLink)
    net.addLink(Phoenix, SanDiego, 1, 1, cls=LINCLink)
    net.addLink(Memphis, Nashville, 1, 2, cls=LINCLink)
    net.addLink(NewYork, Newark, 1, 0, cls=LINCLink)
    net.addLink(NewYork, Scranton, 2, 0, cls=LINCLink)
    net.addLink(NewYork, Wilmington, 3, 0, cls=LINCLink)
    net.addLink(Miami, Tampa, 0, 0, cls=LINCLink)
    net.addLink(Miami, WestPalmBeach, 1, 0, cls=LINCLink)
    net.addLink(Tallahassee, Tampa, 1, 1, cls=LINCLink)
    net.addLink(Newark, Philadelphia, 1, 1, cls=LINCLink)
    net.addLink(Scranton, Syracuse, 3, 2, cls=LINCLink)
    net.addLink(Norfolk, Raleigh, 0, 2, cls=LINCLink)
    net.addLink(Norfolk, Wilmington, 1, 1, cls=LINCLink)
    net.addLink(SanFrancisco, SanJose, 1, 0, cls=LINCLink)
    net.addLink(Portland, SaltLakeCity, 1, 3, cls=LINCLink)
    net.addLink(Portland, Sacramento, 0, 1, cls=LINCLink)
    net.addLink(Portland, Seattle, 2, 0, cls=LINCLink)
    net.addLink(Seattle, Spokane, 1, 1, cls=LINCLink)
    net.addLink(SanJose, SantaBarbara, 1, 1, cls=LINCLink)

    ###### Start of static Mininet epilogue ######
    # Set up logging etc.
    lg.setLogLevel('info')
    lg.setLogLevel('output')

    # Start the network and prime other ARP caches
    net.start()
    net.staticArp()

    # Enter CLI mode
    output("Network ready\n")
    output("Press Ctrl-d or type exit to quit\n")
    CLI(net)
    net.stop()

start()

