#!/usr/bin/env python

from optical import LINCNet, LINCSwitch, LINCLink

from mininet.node import OVSSwitch, RemoteController
from mininet.cli import CLI
from mininet.net import Mininet
from mininet.log import lg, info, error, debug, output

def start(ip="127.0.0.1",port=6633):

    # Set up logging etc.
    lg.setLogLevel('info')
    lg.setLogLevel('output')

    ctrlr = lambda n: RemoteController(n, ip=ip, port=port, inNamespace=False)
    net = LINCNet(switch=OVSSwitch, controller=ctrlr, listenPort=6635)
    c1 = net.addController('c1')

    ####### End of static Mininet prologue ######

    Denver = net.addSwitch('s1', dpid='00:00:00:00:00:01', cls=LINCSwitch)
    SaltLakeCity = net.addSwitch('s2', dpid='00:00:00:00:00:02', cls=LINCSwitch)
    Sacramento = net.addSwitch('s3', dpid='00:00:00:00:00:03', cls=LINCSwitch)
    Phoenix = net.addSwitch('s4', dpid='00:00:00:00:00:04', cls=LINCSwitch)
    ElPaso = net.addSwitch('s5', dpid='00:00:00:00:00:05', cls=LINCSwitch)
    SanDiego = net.addSwitch('s6', dpid='00:00:00:00:00:06', cls=LINCSwitch)
    Albuquerque = net.addSwitch('s7', dpid='00:00:00:00:00:07', cls=LINCSwitch)
    Tampa = net.addSwitch('s8', dpid='00:00:00:00:00:08', cls=LINCSwitch)
    Miami = net.addSwitch('s9', dpid='00:00:00:00:00:09', cls=LINCSwitch)
    Tallahassee = net.addSwitch('s10', dpid='00:00:00:00:00:0a', cls=LINCSwitch)
    Jacksonville = net.addSwitch('s11', dpid='00:00:00:00:00:0b', cls=LINCSwitch)
    BatonRouge = net.addSwitch('s12', dpid='00:00:00:00:00:0c', cls=LINCSwitch)
    OklahomaCity = net.addSwitch('s13', dpid='00:00:00:00:00:0d', cls=LINCSwitch)
    Dallas = net.addSwitch('s14', dpid='00:00:00:00:00:0e', cls=LINCSwitch)
    KansasCity = net.addSwitch('s15', dpid='00:00:00:00:00:0f', cls=LINCSwitch)
    StLouis = net.addSwitch('s16', dpid='00:00:00:00:00:10', cls=LINCSwitch)
    Chicago = net.addSwitch('s17', dpid='00:00:00:00:00:11', cls=LINCSwitch)
    Indianapolis = net.addSwitch('s18', dpid='00:00:00:00:00:12', cls=LINCSwitch)
    Detroit = net.addSwitch('s19', dpid='00:00:00:00:00:13', cls=LINCSwitch)
    SanFrancisco = net.addSwitch('s20', dpid='00:00:00:00:00:14', cls=LINCSwitch)
    SanJose = net.addSwitch('s21', dpid='00:00:00:00:00:15', cls=LINCSwitch)
    WashingtonDC = net.addSwitch('s22', dpid='00:00:00:00:00:16', cls=LINCSwitch)
    Baltimore = net.addSwitch('s23', dpid='00:00:00:00:00:17', cls=LINCSwitch)
    Philadelphia = net.addSwitch('s24', dpid='00:00:00:00:00:18', cls=LINCSwitch)
    Akron = net.addSwitch('s25', dpid='00:00:00:00:00:19', cls=LINCSwitch)
    Pittsburgh = net.addSwitch('s26', dpid='00:00:00:00:00:1a', cls=LINCSwitch)
    Cleveland = net.addSwitch('s27', dpid='00:00:00:00:00:1b', cls=LINCSwitch)
    Toledo = net.addSwitch('s28', dpid='00:00:00:00:00:1c', cls=LINCSwitch)
    Columbus = net.addSwitch('s29', dpid='00:00:00:00:00:1d', cls=LINCSwitch)
    Louisville = net.addSwitch('s30', dpid='00:00:00:00:00:1e', cls=LINCSwitch)
    Cincinnati = net.addSwitch('s31', dpid='00:00:00:00:00:1f', cls=LINCSwitch)
    CharlestonWV = net.addSwitch('s32', dpid='00:00:00:00:00:20', cls=LINCSwitch)
    Nashville = net.addSwitch('s33', dpid='00:00:00:00:00:21', cls=LINCSwitch)
    Birmingham = net.addSwitch('s34', dpid='00:00:00:00:00:22', cls=LINCSwitch)
    Charlotte = net.addSwitch('s35', dpid='00:00:00:00:00:23', cls=LINCSwitch)
    Atlanta = net.addSwitch('s36', dpid='00:00:00:00:00:24', cls=LINCSwitch)
    Shreveport = net.addSwitch('s37', dpid='00:00:00:00:00:25', cls=LINCSwitch)
    Billings = net.addSwitch('s38', dpid='00:00:00:00:00:26', cls=LINCSwitch)
    DesMoines = net.addSwitch('s39', dpid='00:00:00:00:00:27', cls=LINCSwitch)
    Houston = net.addSwitch('s40', dpid='00:00:00:00:00:28', cls=LINCSwitch)
    SanAntonio = net.addSwitch('s41', dpid='00:00:00:00:00:29', cls=LINCSwitch)
    LittleRock = net.addSwitch('s42', dpid='00:00:00:00:00:2a', cls=LINCSwitch)
    NewYork = net.addSwitch('s43', dpid='00:00:00:00:00:2b', cls=LINCSwitch)
    Seattle = net.addSwitch('s44', dpid='00:00:00:00:00:2c', cls=LINCSwitch)
    Portland = net.addSwitch('s45', dpid='00:00:00:00:00:2d', cls=LINCSwitch)
    Spokane = net.addSwitch('s46', dpid='00:00:00:00:00:2e', cls=LINCSwitch)
    Eugene = net.addSwitch('s47', dpid='00:00:00:00:00:2f', cls=LINCSwitch)
    Oakland = net.addSwitch('s48', dpid='00:00:00:00:00:30', cls=LINCSwitch)
    Wichita = net.addSwitch('s49', dpid='00:00:00:00:00:31', cls=LINCSwitch)
    SantaBarbara = net.addSwitch('s50', dpid='00:00:00:00:00:32', cls=LINCSwitch)
    LosAngeles = net.addSwitch('s51', dpid='00:00:00:00:00:33', cls=LINCSwitch)
    Riverside = net.addSwitch('s52', dpid='00:00:00:00:00:34', cls=LINCSwitch)
    Buffalo = net.addSwitch('s53', dpid='00:00:00:00:00:35', cls=LINCSwitch)
    Albany = net.addSwitch('s54', dpid='00:00:00:00:00:36', cls=LINCSwitch)
    Boston = net.addSwitch('s55', dpid='00:00:00:00:00:37', cls=LINCSwitch)
    Newark = net.addSwitch('s56', dpid='00:00:00:00:00:38', cls=LINCSwitch)
    Richmond = net.addSwitch('s57', dpid='00:00:00:00:00:39', cls=LINCSwitch)
    Raleigh = net.addSwitch('s58', dpid='00:00:00:00:00:3a', cls=LINCSwitch)
    Orlando = net.addSwitch('s59', dpid='00:00:00:00:00:3b', cls=LINCSwitch)
    LasVegas = net.addSwitch('s60', dpid='00:00:00:00:00:3c', cls=LINCSwitch)
    net.addLink(Denver, SaltLakeCity, 0, 0, cls=LINCLink)
    net.addLink(Denver, Albuquerque, 3, 1, cls=LINCLink)
    net.addLink(Denver, Wichita, 2, 2, cls=LINCLink)
    net.addLink(Sacramento, SaltLakeCity, 0, 1, cls=LINCLink)
    net.addLink(Sacramento, Oakland, 2, 0, cls=LINCLink)
    net.addLink(Phoenix, ElPaso, 0, 0, cls=LINCLink)
    net.addLink(Phoenix, SanDiego, 1, 0, cls=LINCLink)
    net.addLink(ElPaso, Dallas, 2, 3, cls=LINCLink)
    net.addLink(Albuquerque, ElPaso, 0, 1, cls=LINCLink)
    net.addLink(Tampa, Miami, 0, 0, cls=LINCLink)
    net.addLink(Tallahassee, Tampa, 0, 1, cls=LINCLink)
    net.addLink(Tallahassee, Jacksonville, 1, 0, cls=LINCLink)
    net.addLink(Jacksonville, Orlando, 2, 0, cls=LINCLink)
    net.addLink(BatonRouge, Tallahassee, 0, 2, cls=LINCLink)
    net.addLink(BatonRouge, Houston, 1, 0, cls=LINCLink)
    net.addLink(OklahomaCity, Dallas, 0, 0, cls=LINCLink)
    net.addLink(Dallas, Shreveport, 2, 1, cls=LINCLink)
    net.addLink(KansasCity, StLouis, 0, 0, cls=LINCLink)
    net.addLink(KansasCity, Wichita, 2, 0, cls=LINCLink)
    net.addLink(Chicago, Indianapolis, 0, 0, cls=LINCLink)
    net.addLink(Chicago, Detroit, 1, 0, cls=LINCLink)
    net.addLink(Chicago, DesMoines, 2, 1, cls=LINCLink)
    net.addLink(Indianapolis, Louisville, 1, 0, cls=LINCLink)
    net.addLink(SanFrancisco, SanJose, 0, 0, cls=LINCLink)
    net.addLink(SanJose, SantaBarbara, 1, 0, cls=LINCLink)
    net.addLink(WashingtonDC, Baltimore, 0, 0, cls=LINCLink)
    net.addLink(WashingtonDC, Richmond, 1, 0, cls=LINCLink)
    net.addLink(Philadelphia, Baltimore, 0, 1, cls=LINCLink)
    net.addLink(Akron, Pittsburgh, 0, 0, cls=LINCLink)
    net.addLink(Cleveland, Akron, 0, 1, cls=LINCLink)
    net.addLink(Cleveland, Toledo, 1, 0, cls=LINCLink)
    net.addLink(Cleveland, Buffalo, 2, 0, cls=LINCLink)
    net.addLink(Toledo, Detroit, 1, 1, cls=LINCLink)
    net.addLink(Columbus, Akron, 0, 2, cls=LINCLink)
    net.addLink(Louisville, StLouis, 4, 2, cls=LINCLink)
    net.addLink(Louisville, CharlestonWV, 2, 0, cls=LINCLink)
    net.addLink(Louisville, Nashville, 3, 0, cls=LINCLink)
    net.addLink(Cincinnati, Toledo, 1, 2, cls=LINCLink)
    net.addLink(Cincinnati, Louisville, 0, 1, cls=LINCLink)
    net.addLink(CharlestonWV, WashingtonDC, 2, 2, cls=LINCLink)
    net.addLink(CharlestonWV, Columbus, 1, 1, cls=LINCLink)
    net.addLink(CharlestonWV, Charlotte, 3, 4, cls=LINCLink)
    net.addLink(Nashville, Birmingham, 1, 0, cls=LINCLink)
    net.addLink(Nashville, Charlotte, 2, 0, cls=LINCLink)
    net.addLink(Birmingham, Shreveport, 2, 0, cls=LINCLink)
    net.addLink(Charlotte, Jacksonville, 2, 1, cls=LINCLink)
    net.addLink(Charlotte, Atlanta, 1, 0, cls=LINCLink)
    net.addLink(Atlanta, Birmingham, 1, 1, cls=LINCLink)
    net.addLink(Shreveport, LittleRock, 2, 0, cls=LINCLink)
    net.addLink(Billings, Denver, 1, 1, cls=LINCLink)
    net.addLink(Billings, DesMoines, 0, 0, cls=LINCLink)
    net.addLink(Billings, Spokane, 2, 0, cls=LINCLink)
    net.addLink(DesMoines, KansasCity, 2, 1, cls=LINCLink)
    net.addLink(Houston, SanAntonio, 1, 0, cls=LINCLink)
    net.addLink(SanAntonio, Dallas, 1, 1, cls=LINCLink)
    net.addLink(LittleRock, StLouis, 1, 1, cls=LINCLink)
    net.addLink(NewYork, Pittsburgh, 0, 1, cls=LINCLink)
    net.addLink(NewYork, Newark, 2, 0, cls=LINCLink)
    net.addLink(Seattle, Portland, 0, 0, cls=LINCLink)
    net.addLink(Portland, Eugene, 1, 0, cls=LINCLink)
    net.addLink(Spokane, Seattle, 1, 1, cls=LINCLink)
    net.addLink(Eugene, Sacramento, 1, 1, cls=LINCLink)
    net.addLink(Oakland, SanFrancisco, 1, 1, cls=LINCLink)
    net.addLink(Wichita, OklahomaCity, 1, 1, cls=LINCLink)
    net.addLink(SantaBarbara, LosAngeles, 1, 0, cls=LINCLink)
    net.addLink(LosAngeles, SanDiego, 1, 1, cls=LINCLink)
    net.addLink(LosAngeles, Riverside, 2, 0, cls=LINCLink)
    net.addLink(Riverside, Sacramento, 1, 3, cls=LINCLink)
    net.addLink(Riverside, LasVegas, 2, 0, cls=LINCLink)
    net.addLink(Buffalo, Albany, 1, 0, cls=LINCLink)
    net.addLink(Albany, Boston, 1, 0, cls=LINCLink)
    net.addLink(Boston, NewYork, 1, 1, cls=LINCLink)
    net.addLink(Newark, Philadelphia, 1, 1, cls=LINCLink)
    net.addLink(Richmond, Raleigh, 1, 0, cls=LINCLink)
    net.addLink(Raleigh, Charlotte, 1, 3, cls=LINCLink)
    net.addLink(Orlando, Miami, 1, 1, cls=LINCLink)
    net.addLink(LasVegas, SaltLakeCity, 1, 2, cls=LINCLink)

    ###### Start of static Mininet epilogue ######
    # Set up logging etc.
    lg.setLogLevel('info')
    lg.setLogLevel('output')

    # Start the network and prime other ARP caches
    net.start()
    net.staticArp()

    # Enter CLI mode
    output("Network ready\n")
    output("Press Ctrl-d or type exit to quit\n")
    CLI(net)
    net.stop()

start()

