LIBNAME = NetCoreLib

MLIFILES = _build/NetCore_Types.mli \
           _build/NetCore_Parser.mli \
           _build/NetCore_Compiler.mli \
           _build/NetCore_Controller.mli \
           _build/NetCore_Stream.mli \
	   _build/NetCore_MacLearning.mli

CMIFILES = $(MLIFILES:.mli=.cmi)

include ../Makefile.common
