.PHONY: all debug native install uninstall doc clean

CMIFILES = $(MLIFILES:.mli=.cmi)

OCAMLBUILD = ocamlbuild -use-ocamlfind 

OCAMLFIND = ocamlfind

all: debug native uninstall install 

debug:
	$(OCAMLBUILD) -cflag -ppopt -cflag -lwt-debug debug.otarget

native:
	$(OCAMLBUILD) native.otarget

install:
	$(OCAMLFIND) install $(LIBNAME) META $(MLIFILES) $(CMIFILES) $(LIBNAME).d.cma $(LIBNAME).cmxa $(LIBNAME).a

uninstall:
	$(OCAMLFIND) remove $(LIBNAME)

clean:
	$(OCAMLBUILD) -clean
