(** Module with static parameters *)
open! Core


(** {2 Parallelization parameters} *)

(** total number of jobs = J + RN * RJ *)

(** number of local jobs *)
let j = Sys.getenv "J" |> function
  | Some j -> Int.of_string j
  | None -> Or_error.ok_exn Linux_ext.cores ()

(** number of remote jobs per remote machine *)
let rj = Sys.getenv "RJ" |> function
  | Some rj -> Int.of_string rj
  | None -> j

(** number of remote servers to use *)
let r = Sys.getenv "RN" |> function
  | Some r -> Int.of_string r
  | None -> 0

(** cluster to use for parallelization  *)
let cluster = Sys.getenv "CLUSTER" |> function
  | Some s ->
    String.split_on_chars s ~on:[' '; '\n'; '\r'; '\t']
    |> List.map ~f:String.strip
    |> List.filter ~f:(fun s -> Unix.gethostname () |> String.equal s |> not)
  | None -> []

(*   List.init 24 ~f:(fun i -> sprintf "atlas-%d" (i+1))
  |> List.filter ~f:(fun s -> Unix.gethostname () |> String.equal s |> not)
  (* prefer atlas servers with higher index *)
  |> List.rev *)


(** {2 PNK program parameters} *)

(** switch field *)
let sw = "sw"

(** port field *)
let pt = "pt"

(** counter field *)
let counter = "failures"

(** ttl field *)
let ttl = "ttl"
let max_ttl = 32

(** Destination host. Files generated by Praveen assume this is 1. *)
let destination = 1

(** up bit associated with link *)
let up sw pt = sprintf "up_%d" pt
let is_up_field f = String.is_prefix ~prefix:"up_" f

(** Extra bit needed for F10 scheme 2 re-routing *)
let f10s2 = "f10s2"

(** equivalence should be modulo these fields *)
let modulo =
  [pt; counter; f10s2; ttl]

(** various files *)
let topo_file base_name = base_name ^ ".dot"
let spf_file base_name = base_name ^ "-spf.trees"
let ecmp_file base_name = base_name ^ "-allsp.nexthops"
let car_file base_name = base_name ^ "-disjointtrees.trees"
let log_file base_name = base_name ^ ".log"
let dump_file ?(ext="json") base_name ~routing_scheme ~max_failures ~failure_prob =
  let scheme = String.tr routing_scheme ~target:' ' ~replacement:'_' in
  let dir, topology = Filename.split base_name in
  let dir = sprintf "%s/results/%s-%s" dir topology scheme in
  let mf = if max_failures < 0 then "inf" else Int.to_string max_failures in
  let p_num, p_den = Prob.to_int_frac failure_prob in
  sprintf "%s/%s-%d-%d.%s" dir mf p_num p_den ext
let dot_file  =
 dump_file ~ext:"dot"

